### ISSUE TITLE
Selecting Monsters breaks the HUD / HUD only works for Players.

### ISSUE THREAD

**Issue by tim-bersau** [chrpow/fvtt-token-action-hud-shadowdark#50] opened 2024-01-28 18:03 UTC
From the version history it sounds like this exact issue was hotfixed at some point, but it's back again. 

I'm no coder, but because this was once a fix that is happening again, I'm wondering if it has to do with this line in the newest version changelog:

_"Implement new NPC data structure from SD 1.6.x by @chrpow in https://github.com/chrpow/fvtt-token-action-hud-shadowdark/pull/47"_

Anyway best of luck I'm a big fan.

https://github.com/chrpow/fvtt-token-action-hud-shadowdark/assets/10822280/e4b45300-90ab-446f-a22c-c162bc0741df

**Comment by chrpow** [comment] 2024-01-28 20:55
Hey! Thanks for bringing this up. I've been away from coding for a while, and the main Shadowdark Foundry VTT team made some big code changes recently that broke some parts of this module. I promise this is a priority!

**Comment by hendelmasad** [comment] 2024-01-31 18:56
I'm getting a lot of weird errors too, it seems related to the HUD. Would a copy of my console log help? 
Foundry v11.315
Windows 11
hosted on the Forge service

I'm getting this message about the HUD: 

Uncaught (in promise) TypeError: this.actor?._populateBackgroundItems is not a function
    at #s (token-action-hud-shadowdark.min.js:1:4594)
    at ActionHandler.buildSystemActions (token-action-hud-shadowdark.min.js:1:4331)
    at #h (action-handler.js:209:20)
    at ActionHandler.buildHud (action-handler.js:100:18)
    at async #It (token-action-hud.js:1157:14)
    at async TokenActionHud.update (token-action-hud.js:1093:20)

There's more in the attached log below. It's thousands of lines long but a lot of repeated error messages.

[gmkeith-shadowdark.forge-vtt.com-1706726849982.log](https://github.com/chrpow/fvtt-token-action-hud-shadowdark/files/14115887/gmkeith-shadowdark.forge-vtt.com-1706726849982.log)

Cheers!

**Comment by chrpow** [comment] 2024-02-03 20:28
Duplicate of #48, fixed with #51

**Closed by chrpow** 2024-02-03 20:28 UTC
